# Official doc of config
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
keybinding:
  universal:
    # prevPage: ',' # default
    # nextPage: '.' # default
    prevPage: '<c-b>' # go to next page in list
    nextPage: '<c-f>' # go to previous page in list

os:
  editCommand: 'nvim' # 您可以根據需要修改為您喜歡的編輯器
  editCommandTemplate: '{{editor}} {{filename}}'
  openCommand: 'open {{filename}}'
# gui:
#     skipDiscardChangeWarning: true
#     theme:
#         activeBorderColor:
#             - red
#             - bold
#         inactiveBorderColor:
#             - white
#         optionsTextColor:
#             - blue
#         selectedLineBgColor:
#             - blue # set to `default` to have no background colour
#         selectedRangeBgColor:
#             - blue
#         cherryPickedCommitBgColor:
#             - cyan
#         cherryPickedCommitFgColor:
#             - blue
#         unstagedChangesColor:
#             - red
#         defaultFgColor:
#             - default
