# Official doc of config
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
keybinding:
  universal:
    # prevPage: ',' # default
    # nextPage: '.' # default
    prevPage: '<c-b>' # go to next page in list
    nextPage: '<c-f>' # go to previous page in list
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim --line={{line}} {{filename}}'
  editAtLineAndWait: 'nvim --block --line={{line}} {{filename}}'
  editInTerminal: true
  openDirInEditor: 'nvim {{dir}}'
gui:
  nerdFontsVersion: "3"
  border: rounded
  useHunkModeInStagingView: false
  theme:
    activeBorderColor: ["#88C0D0", bold]
    inactiveBorderColor: ["#4C566A"]
    selectedLineBgColor: ["#434C5E"]
    defaultFgColor: ["#D8DEE9"]
git:
  pagers:
    - pager: "delta --paging=never --line-numbers --line-numbers-left-format=\"\" --syntax-theme=Nord --minus-style=\"syntax #3B2C37\" --minus-emph-style=\"syntax #BF616A\" --plus-style=\"syntax #2B3840\" --plus-emph-style=\"syntax #A3BE8C\""
  autoFetch: true
  log:
    showGraph: always
customCommands:
  - key: "<c-p>"
    context: "global"
    command: "git push"
    description: "Push"
  - key: "F"
    context: "global"
    command: "git fetch --all --prune"
    description: "Fetch all and prune"
  - key: "W"
    context: "files"
    command: "git add -p"
    description: "Interactive staging"
    output: terminal
