# Official doc of config
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
keybinding:
  universal:
    # prevPage: ',' # default
    # nextPage: '.' # default
    prevPage: '<c-b>' # go to next page in list
    nextPage: '<c-f>' # go to previous page in list

os:
  edit: 'nvim' # 新的編輯器設定
  editAtLine: 'nvim +{{line}} {{filename}}' # 可以跳到特定行的設定
  open: 'open {{filename}}' # 開啟檔案的指令
# gui:
#     skipDiscardChangeWarning: true
#     theme:
#         activeBorderColor:
#             - red
#             - bold
#         inactiveBorderColor:
#             - white
#         optionsTextColor:
#             - blue
#         selectedLineBgColor:
#             - blue # set to `default` to have no background colour
#         selectedRangeBgColor:
#             - blue
#         cherryPickedCommitBgColor:
#             - cyan
#         cherryPickedCommitFgColor:
#             - blue
#         unstagedChangesColor:
#             - red
#         defaultFgColor:
#             - default
