[manager]
show_hidden = true
sort_dir_first = true
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
linemode = "size"

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]
open = [
  { run = 'open "$@"', for = "macos" },
  { run = 'xdg-open "$@"', for = "linux" },
]
reveal = [
  { run = 'open -R "$@"', for = "macos" },
]

[tasks]
micro_workers = 10
macro_workers = 25
bizarre_retry = 5
